<?php
Main::$APPLICATION_NAME = '{{APP_NAME}}';
Main::$ROOT_DOMAIN = '{{ROOT_DOMAIN}}';
Main::$MEMCACHE_SERVERS = '{{MEMCACHE}}';
Main::$STORAGE_SERVERS = '{{STORAGE}}';
Main::$DATABASE_SERVERS = '{{DATABASE}}';
